name: Deploy React Application

on:
  push:
    branches:
      - mern-ec2-docker-ssl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            -t brajesh20/studysphere_frontend:latest \
            --build-arg REACT_APP_NODE_ENV=production \
            --build-arg REACT_APP_SERVER_BASE_URL=${{ secrets.REACT_APP_SERVER_BASE_URL }} \
            --build-arg VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }} \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            .

      - name: Publish Image to Docker Hub
        run: docker push brajesh20/studysphere_frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull brajesh20/studysphere_frontend:latest

      - name: Delete Old Container
        run: docker rm -f reactjs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d \
            --restart unless-stopped \
            -p 3000:80 \
            --name reactjs-app-container \
            brajesh20/studysphere_frontend:latest
